baseurl: "/ict-balie"

repo: "https://github.com/Pius-X-Antwerpen/ict-balie"
github_user: "Pius-X-Antwerpen"
github_repo: "pius-x-antwerpen.github.io/ict-balie"


collections:
    tutorials:
        output: true

defaults:
    - scope:
          path: ""
      values:
          activity: "home"
    - scope:
          path: "_tutorials"
      values:
          activity: "tutorials"
          excerpt_separator: "<!--more-->"

exclude:
    - "*.draft.md"